

name: Update Drop Charts

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  update-drop-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            ref: main

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10' 
    
      - name: Install Dependencies
        run: cd ./updater && pip install -r requirements.txt

      - name: Run Updater Script
        run: cd ./updater && python dropchart_updater.py

      - name: Commit and Push Updates
        id: pushupdate
        continue-on-error: true
        env: 
          CI_COMMIT_MESSAGE: 'ci: update dropcharts'
          CI_COMMIT_AUTHOR: Github Actions
          CI_BRANCH: dropchart_update
        run: |
          cd './Monster Scouter/Drops/'
          git branch -D "${{ env.CI_BRANCH }}" || true
          git push origin --delete "${{ env.CI_BRANCH }}" || true
          git checkout -b "${{ env.CI_BRANCH }}"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "actions@users.noreply.github.com"
          git add *.lua
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" \
            && git push -u origin "${{ env.CI_BRANCH }}" \
            || echo "NOCHANGES=true" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        if: ${{ steps.pushupdate.outputs.NOCHANGES != 'true' }}
        run: gh pr create -B main -H dropchart_update --title 'Update Drop Charts' --body 'Review the Changes and Approve and Merge if good.'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

